---

- hosts: "{{host}}"
  connection: local
  become: true

  vars:
    messages: []

  tasks:

  - name: change hostname
    hostname:
      name: endava

  - name: Store Vars
    shell: "ls -1D /home/bopopa/*"
    register: output

  - name: debug module
    debug: msg={{ item }}
    loop: "{{output.stdout_lines}}"

  post_tasks:
  - name: Print informations messages
    debug:
      msg: 
        - "Informational Message:"
        - "======================"
        - "{{ messages }}"
    when: messages|length > 0
    delegate_to: localhost 
